# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6a2c4432fc47e571b30da9980fddacedadaa27c47eb4fbc866f8eeab34138f61a26d51bfd8f9bb042bd56cca25aad77ff6b87ea4afcaa5fd399b73b8030fe32

test:
  secret_key_base: 0ccd74cff313ad0f103dc8543ebfa9973a7a7aaca04bebc31db13c8bac5c429fcb97968cbc7f21e08786e8b26051c4fd8a12b14043bb562c6d98999dce0c39e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
